### ISSUE TITLE
对Compact有点疑惑

### ISSUE THREAD

**Issue by TaoXieSZ** [chenjiandongx/grogudb#4]
大佬你好，最近对数据库比较感兴趣，在看你的源码，发现Compact可能有点逻辑问题
https://github.com/chenjiandongx/grogudb/blob/b083d1d15e047d8782302e99546c75683099a71c/compaction.go#L138-L143
先对group降序排序，也就是最新的group会在前面
https://github.com/chenjiandongx/grogudb/blob/b083d1d15e047d8782302e99546c75683099a71c/segment.go#L247-L251
然后doCompact时：
https://github.com/chenjiandongx/grogudb/blob/b083d1d15e047d8782302e99546c75683099a71c/compaction.go#L250-L252
此时last指的是最后一个diskSegment，那按理说应该是seqID是最小的。前后有矛盾了。

如果说得不对麻烦指正 😄

**Comment by chenjiandongx** [comment]
@TaoXieSZ https://github.com/chenjiandongx/grogudb/pull/6

可以帮忙 review 一下代码
